package com.example.demo.types

enum class ActivityType {
    EXPLORE, STREET_FOOD, WALK, RELAX, MUSEUM, SIGHTSEEING, HOTEL, EAT, EXTREME_SPORTS, OFF_ROAD, CLIMBING, CONGRESS, LECTURE, SCIENCE, OTHER
}